title: Jinu Hyun
description: 
logo: /assets/images/profile.jpg
show_downloads: false
google_analytics:
url: https://itsjinuhyun.github.io
baseurl: ""
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  blog:
    output: true
    permalink: /blog/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "default"

github:
  is_project_page: false 